KubeRocketCI/docs

- docs/operator-guide/argocd-integration.md
- docs/operator-guide/artifacts-verification.md
- docs/operator-guide/external-secrets-operator-integration.md
- docs/operator-guide/install-external-secrets-operator.md
- docs/operator-guide/install-loki.md
- docs/operator-guide/install-velero.md
- docs/operator-guide/kibana-ilm-rollover.md
- docs/operator-guide/manage-custom-certificate.md
- docs/operator-guide/multitenant-logging.md
- docs/operator-guide/oauth2-proxy.md
- docs/operator-guide/upgrade-edp-3.1.md
- docs/operator-guide/upgrade-edp-3.2.md
- docs/operator-guide/upgrade-edp-3.3.md
- docs/operator-guide/upgrade-edp-3.4.md
- docs/operator-guide/upgrade-edp-3.5.md
- docs/operator-guide/upgrade-edp-3.6.md
- docs/operator-guide/upgrade-edp-3.7.md
- docs/operator-guide/upgrade-edp-3.8.md
- docs/operator-guide/upgrade-keycloak-19.0.md
* Platform Capabilities block
* Upgrade block
* FAQ block
> docs: Update  operator-guide section

- docs/operator-guide/upgrade/upgrade-edp-3.9.md
- sidebars.ts
- versioned_docs/version-3.9.0/operator-guide/upgrade/upgrade-edp-3.9.md
- versioned_sidebars/version-3.9.0-sidebars.json
> docs: Upgrade Documentation for KubeRocketCI 3.9.0

- docs/operator-guide/install-kuberocketci.md
- versioned_docs/version-3.9.0/operator-guide/install-kuberocketci.md
> docs: Refactor Install KRCI page

- docs/operator-guide/aws-marketplace-install.md
- versioned_docs/version-3.9.0/operator-guide/aws-marketplace-install.md
Refactor AWS Marketplace guide
> docs: Refactor AWS Marketplace guide

- package-lock.json
- package.json
- src/css/custom.css
- src/features/home/components/Features/styles.module.css
- src/features/home/components/Hero/index.tsx
- src/features/home/components/Hero/styles.module.css
- src/features/pricing/components/Card/styles.module.css
- src/theme/Root.tsx
- yarn.lock
Add cookie consent
Fix ui bugs
> docs: Add cookie consent

- src/css/custom.css
- src/theme/Root.tsx
> docs: Fix nav link color

- src/theme/Root.tsx
Update cookie consent expire time 
> docs: Update cookie consent expire

- docs/developer-guide/annotations-and-labels.md
> chore: Update labels documentation

- docs/faq/pipelines.md
- docs/operator-guide/troubleshooting/review-pipeline-is-failed.md
> chore: Update VCS trigger FAQ documentation

- docs/operator-guide/auth/configure-keycloak-oidc-eks.md
- docs/operator-guide/auth/eks-oidc-integration.md
Updated subsections:
- https://docs.kuberocketci.io/docs/operator-guide/auth/eks-oidc-integration
- https://docs.kuberocketci.io/docs/operator-guide/auth/configure-keycloak-oidc-eks
> docs: Update EKS OIDC integration with keycloak pages

- docs/operator-guide/project-management-and-reporting/reportportal-keycloak.md
- versioned_docs/version-3.9.0/operator-guide/auth/configure-keycloak-oidc-eks.md
- versioned_docs/version-3.9.0/operator-guide/auth/eks-oidc-integration.md
- versioned_docs/version-3.9.0/operator-guide/project-management-and-reporting/reportportal-keycloak.md
Updated subsections:
- https://docs.kuberocketci.io/docs/next/operator-guide/project-management-and-reporting/reportportal-keycloak
> docs: Update Report-portal Keycloak integration section

- docs/about-platform.md
> docs: Add c/cpp language support

- docs/developer-guide/annotations-and-labels.md
Updated subsections: 
- https://docs.kuberocketci.io/docs/next/developer-guide/annotations-and-labels
> docs: Update labels documentation

- .github/ISSUE_TEMPLATE/.github/workflows/ci.yml
- docs/user-guide/add-cd-pipeline.md
> chore: Add simple ci check

- docs/operator-guide/auth/platform-auth-model.md
- versioned_docs/version-3.9.0/operator-guide/auth/platform-auth-model.md
Updated subsections:
- https://docs.kuberocketci.io/docs/operator-guide/auth/platform-auth-model
> docs: Update authentication overview section

- src/features/home/components/Hero/index.tsx
- src/features/pricing/index.tsx
> docs: Add h1

- docs/operator-guide/auth/configure-keycloak-oidc-eks.md
- docs/operator-guide/auth/oauth2-proxy.md
- docs/operator-guide/auth/platform-auth-model.md
- docs/operator-guide/auth/ui-portal-oidc.md
- sidebars.ts
- versioned_docs/version-3.9.0/operator-guide/auth/configure-keycloak-oidc-eks.md
- versioned_docs/version-3.9.0/operator-guide/auth/oauth2-proxy.md
- versioned_docs/version-3.9.0/operator-guide/auth/platform-auth-model.md
- versioned_docs/version-3.9.0/operator-guide/auth/ui-portal-oidc.md
- versioned_sidebars/version-3.9.0-sidebars.json
> docs: Align the auth documentation with the latest changes

- docs/operator-guide/auth/platform-auth-model.md
- versioned_docs/version-3.9.0/operator-guide/auth/platform-auth-model.md
> docs: Remove deprecated groups

- docs/operator-guide/auth/configure-keycloak-oidc-eks.md
- docs/operator-guide/auth/eks-oidc-integration.md
- docs/operator-guide/auth/keycloak.md
- docs/operator-guide/auth/ui-portal-oidc.md
- versioned_docs/version-3.9.0/operator-guide/auth/configure-keycloak-oidc-eks.md
- versioned_docs/version-3.9.0/operator-guide/auth/eks-oidc-integration.md
- versioned_docs/version-3.9.0/operator-guide/auth/keycloak.md
- versioned_docs/version-3.9.0/operator-guide/auth/ui-portal-oidc.md
> docs: Align OIDC helm chart name

- docs/operator-guide/auth/configure-keycloak-oidc-eks.md
- versioned_docs/version-3.9.0/operator-guide/auth/configure-keycloak-oidc-eks.md
> docs: Enhance EKS OIDC documentation

- src/features/pricing/constants.ts
- src/features/pricing/index.tsx
- https://docs.kuberocketci.io/pricing
> chore: Update pricing page content

- .prettierignore
- .prettierrc.json
- package.json
- src/components/Note/index.tsx
- src/components/NoteAsterisk/index.tsx
- src/features/pricing/components/Card/index.tsx
- src/features/pricing/index.tsx
- src/features/pricing/list.tsx
- src/features/pricing/styles.module.css
- src/features/pricing/types.ts
- src/theme/BlogPostPage/index.tsx
- Update asterisks size and location
- Fix npm scripts
- Adjust prettier config(remove unneeded properties)
> docs: Update asterisks, fix npm scripts, adjust prettier cfg

- docs/operator-guide/install-kuberocketci.md
- docs/quick-start/platform-installation.md
- versioned_docs/version-3.10.0/operator-guide/install-kuberocketci.md
- versioned_docs/version-3.10.0/quick-start/platform-installation.md
> chore: Bump version to 3.10.0

- docs/supported-versions.md
- yarn.lock
This change updates the "Supported Versions and Compatibility" page in KubeRocketCI documentation.
The `npm start` command runs with no fails.
> docs: Update supported versions page (#311)

- docs/operator-guide/auth/platform-auth-model.md
- versioned_docs/version-3.10.0/operator-guide/auth/platform-auth-model.md
- versioned_docs/version-3.9.0/operator-guide/auth/platform-auth-model.md
> docs: Align rbac for developers group

- docs/operator-guide/install-kuberocketci.md
- docs/quick-start/platform-installation.md
- versioned_docs/version-3.10/operator-guide/install-kuberocketci.md
- versioned_docs/version-3.10/quick-start/platform-installation.md
This minor change updates KubeRocketCI version in documentation so users will install the latest version of KubeRocketCI
The "npm ci && npm start" command works properly.
> docs: Update KubeRocketCI version in documentation (#339)

- docs/operator-guide/extensions/krakend.md
- versioned_docs/version-3.10/operator-guide/extensions/krakend.md
Align integrate krakenD widget guide
The full integration of KrakenD with the KuberocketCI platform version 3.10.2 was successfully completed following the provided guide.
> docs: Align integrate krakend widget guide(#330)

- cspell.config.yaml
- docs/operator-guide/upgrade/upgrade-edp-3.10.md
- sidebars.ts
- versioned_docs/version-3.10/operator-guide/upgrade/upgrade-edp-3.10.md
- versioned_docs/version-3.9/operator-guide/upgrade/upgrade-edp-3.10.md
- versioned_sidebars/version-3.10-sidebars.json
- versioned_sidebars/version-3.9-sidebars.json
Add upgrade guide for platform version 3.9.0 to 3.10.2
> chore: Add upgrade guide for platform version 3.9.0 to 3.10.2

- docs/operator-guide/infrastructure-providers/aws/deploy-aws-eks.md
- versioned_docs/version-3.10/operator-guide/infrastructure-providers/aws/deploy-aws-eks.md
- versioned_docs/version-3.9/operator-guide/infrastructure-providers/aws/deploy-aws-eks.md
- Renamed `providers.tf` to `versions.tf`.
> chore: Rename providers.tf to versions.tf

- docs/operator-guide/auth/platform-auth-model.md
- versioned_docs/version-3.10/operator-guide/auth/platform-auth-model.md
- versioned_docs/version-3.9/operator-guide/auth/platform-auth-model.md
> Align sonar group names

- cspell.config.yaml
- docs/operator-guide/extensions/krakend.md
- https://docs.kuberocketci.io/docs/operator-guide/extensions/krakend
> chore: Update KrakenD integration section

- blog/2024-12-03/aws-eks-microsoft-entra-oidc-integration.md
- https://docs.kuberocketci.io/blog/integrating-oidc-authentication-microsoft-entra-aws-eks
> docs: Update blog post about Microsoft Entra Auth process

- docs/operator-guide/extensions/krakend.md
- docs/operator-guide/install-kuberocketci.md
- docs/operator-guide/upgrade/upgrade-edp-3.10.md
- docs/quick-start/platform-installation.md
- docs/supported-versions.md
- versioned_docs/version-3.10/operator-guide/extensions/krakend.md
- versioned_docs/version-3.10/operator-guide/install-kuberocketci.md
- versioned_docs/version-3.10/operator-guide/upgrade/upgrade-edp-3.10.md
- versioned_docs/version-3.10/quick-start/platform-installation.md
- versioned_docs/version-3.10/supported-versions.md
- versioned_docs/version-3.9/operator-guide/upgrade/upgrade-edp-3.10.md
> Align EDP Install Documentation to 3.10.3

- docs/operator-guide/install-argocd.md
- versioned_docs/version-3.10/operator-guide/install-argocd.md
- versioned_docs/version-3.9/operator-guide/install-argocd.md
> Update argocd install documentation

- docs/operator-guide/artifacts-management/nexus-sonatype.md
- docs/operator-guide/artifacts-management/package-registry.md
- versioned_docs/version-3.10/operator-guide/artifacts-management/nexus-sonatype.md
- versioned_docs/version-3.10/operator-guide/artifacts-management/package-registry.md
- versioned_docs/version-3.9/operator-guide/artifacts-management/nexus-sonatype.md
- versioned_docs/version-3.9/operator-guide/artifacts-management/package-registry.md
> Update Naming Convention for Nexus-Operator Resources

- docs/operator-guide/microsoft-entra/oidc-authentication-overview.md
- versioned_docs/version-3.10/operator-guide/microsoft-entra/oidc-authentication-overview.md
- versioned_docs/version-3.9/operator-guide/microsoft-entra/oidc-authentication-overview.md
- https://docs.kuberocketci.io/docs/next/operator-guide/microsoft-entra/oidc-authentication-overview
> docs: Update Microsoft Entra Overview page

- docs/operator-guide/install-tekton.md
- versioned_docs/version-3.10/operator-guide/install-tekton.md
- versioned_docs/version-3.9/quick-start/platform-installation.md
- https://docs.kuberocketci.io/docs/quick-start/platform-installation
> docs: Update Tekton installation guide

- cspell.config.yaml
- docs/user-guide/application-sonarqube-project-properties.md
- sidebars.ts
- versioned_docs/version-3.10/user-guide/application-sonarqube-project-properties.md
- versioned_docs/version-3.9/user-guide/application-sonarqube-project-properties.md
- versioned_sidebars/version-3.10-sidebars.json
- versioned_sidebars/version-3.9-sidebars.json
This is a user-guide how to set the SonarQube project properties to meet all application requirements.
> docs: Add user-guide configure sonarqube project properties

- docs/use-cases/application-scaffolding.md
- docs/user-guide/gitops.md
- versioned_docs/version-3.10/use-cases/application-scaffolding.md
- versioned_docs/version-3.10/user-guide/gitops.md
This minor change updates pipeline naming pattern in a couple of documentation pages.
Fixes #(issue)
`npm ci && npm start`
> docs: Update pipeline naming pattern in docs (#389)

- package-lock.json
- package.json
- src/theme/Root.tsx
- static/css/cookie-consent.css
- yarn.lock
> feat: Add cookie pro consent widget

- docusaurus.config.ts
> fix: Fix env check condition in docusaurus cfg

- static/css/cookie-consent.css
> fix: Cookie consent css

- docusaurus.config.ts
> chore: Remove gtag

- docs/operator-guide/upgrade/upgrade-edp-3.10.md
- versioned_docs/version-3.10/operator-guide/upgrade/upgrade-edp-3.10.md
- versioned_docs/version-3.9/operator-guide/upgrade/upgrade-edp-3.10.md
- https://docs.kuberocketci.io/docs/next/operator-guide/upgrade/upgrade-edp-3.10/
> docs: Update upgrade guide for v3.10

- docs/about-platform.md
- docs/user-guide/add-autotest.md
> Add java 21 framework

- docs/operator-guide/upgrade/upgrade-edp-3.10.md
- versioned_docs/version-3.10/operator-guide/upgrade/upgrade-edp-3.10.md
- versioned_docs/version-3.9/operator-guide/upgrade/upgrade-edp-3.10.md
This tiny change fixes a notion in the "Upgrade KRCI to 3.10" page.
> docs: Update upgrade edp 3-10 page (#397)

- docs/operator-guide/auth/platform-auth-model.md
- versioned_docs/version-3.10/operator-guide/auth/platform-auth-model.md
- https://docs.kuberocketci.io/docs/next/operator-guide/auth/platform-auth-model/
> docs: Describe Keycloak groups permissions

- docs/about-platform.md
- docs/basic-concepts.md
- docs/compliance.md
- docs/glossary.md
- docs/quick-start/create-application.md
- docs/quick-start/deploy-application.md
- docs/quick-start/integrate-argocd.md
- docs/quick-start/integrate-container-registry.md
- docs/quick-start/integrate-github.md
- docs/quick-start/integrate-sonarcloud.md
- docs/quick-start/platform-installation.md
- docs/quick-start/quick-start-overview.md
- docs/supported-versions.md
- versioned_docs/version-3.10/about-platform.md
- versioned_docs/version-3.10/basic-concepts.md
- versioned_docs/version-3.10/compliance.md
- versioned_docs/version-3.10/glossary.md
- versioned_docs/version-3.10/quick-start/create-application.md
- versioned_docs/version-3.10/quick-start/deploy-application.md
- versioned_docs/version-3.10/quick-start/integrate-argocd.md
- versioned_docs/version-3.10/quick-start/integrate-container-registry.md
- versioned_docs/version-3.10/quick-start/integrate-github.md
- versioned_docs/version-3.10/quick-start/integrate-sonarcloud.md
- versioned_docs/version-3.10/quick-start/platform-installation.md
- versioned_docs/version-3.10/quick-start/quick-start-overview.md
- versioned_docs/version-3.10/supported-versions.md
This change adds metadata to the getting started section of the product's documentation.
npm ci && npm start. SEO META in 1 CLICK.
> docs: Add metadata to getting started section (#405)

- staticwebapp.config.json
> chore: Update CSP

- docs/operator-guide/infrastructure-providers/aws/enable-irsa.md
- versioned_docs/version-3.10/operator-guide/infrastructure-providers/aws/enable-irsa.md
- versioned_docs/version-3.11/operator-guide/infrastructure-providers/aws/enable-irsa.md
- versioned_docs/version-3.9/operator-guide/infrastructure-providers/aws/enable-irsa.md
> docs: Update IRSA test image

- .vscode/settings.json
- docs/operator-guide/infrastructure-providers/atlantis-installation.md
- versioned_docs/version-3.10/operator-guide/infrastructure-providers/atlantis-installation.md
- versioned_docs/version-3.11/operator-guide/infrastructure-providers/atlantis-installation.md
- versioned_docs/version-3.9/operator-guide/infrastructure-providers/atlantis-installation.md
Update atlantis integration section
> docs: Update atlantis installation section

- docs/operator-guide/artifacts-management/nexus-image-registry.md
- versioned_docs/version-3.10/operator-guide/artifacts-management/nexus-image-registry.md
- versioned_docs/version-3.11/operator-guide/artifacts-management/nexus-image-registry.md
- versioned_docs/version-3.9/operator-guide/artifacts-management/nexus-image-registry.md
Align nexus installation guide
Deployed in test environment
> chore: Align nexus installation guide

- cspell.config.yaml
- docs/operator-guide/upgrade/upgrade-edp-3.11.md
- versioned_docs/version-3.10/operator-guide/upgrade/upgrade-edp-3.11.md
- versioned_docs/version-3.11/operator-guide/upgrade/upgrade-edp-3.11.md
- versioned_docs/version-3.9/operator-guide/upgrade/upgrade-edp-3.11.md
- https://docs.kuberocketci.io/docs/next/operator-guide/upgrade/upgrade-edp-3.11
> docs: Update upgrade guide for v3.11

- docs/operator-guide/deploy-aws-eks.md
- docs/operator-guide/infrastructure-providers/atlantis-installation.md
- versioned_docs/version-3.10/operator-guide/deploy-aws-eks.md
- versioned_docs/version-3.10/operator-guide/infrastructure-providers/atlantis-installation.md
- versioned_docs/version-3.11/operator-guide/deploy-aws-eks.md
- versioned_docs/version-3.11/operator-guide/infrastructure-providers/atlantis-installation.md
- versioned_docs/version-3.9/operator-guide/deploy-aws-eks.md
- versioned_docs/version-3.9/operator-guide/infrastructure-providers/atlantis-installation.md
- Update `Atlantis Installation` guide.
- Update `Deploy AWS EKS Cluster` guide.
> docs: Update Atlantis Installation guide

- .github/workflows/azure-static-web-apps-gentle-pebble-0839af61e.yml
- .github/workflows/ci.yml
> chore: Address codeql recommendations

- docs/operator-guide/install-tekton.md
- versioned_docs/version-3.11/operator-guide/install-tekton.md
- https://docs.kuberocketci.io/docs/next/operator-guide/install-tekton
> docs: Align Tekton stack versions

- docs/quick-start/platform-installation.md
- docs/use-cases/custom-pipelines-flow.md
- versioned_docs/version-3.10/use-cases/custom-pipelines-flow.md
- versioned_docs/version-3.11/quick-start/platform-installation.md
- versioned_docs/version-3.11/use-cases/custom-pipelines-flow.md
This change updates the required Tekton versions for release 3.11 and 3.12 in the [Quick Start Guide](https://docs.kuberocketci.io/docs/quick-start/platform-installation#install-tekton).
Besides, it add a smal note to the [Create and Use Custom Tekton Pipelines](https://docs.kuberocketci.io/docs/use-cases/custom-pipelines-flow#deliver-custom-tekton-pipelines-to-the-cluster).
npm ci && npm start && yarn spell-check
> docs: Update Tekton versions in quick guide (#480)

- docusaurus.config.ts
> chore: Update sitemap config

- .cursor/rules/.krci-ai/tw.mdc
- .krci-ai/agents/tw.yaml
- .krci-ai/tasks/doc-build.md
- .krci-ai/tasks/doc-design.md
- .krci-ai/tasks/doc-review.md
Called the agent in the Cursor chat and verified that it worked.
> feat: Update TW agent (#290)

- src/css/custom.css
Tryfix for dark theme styles not working correctly
> docs: Tryfix dark theme

- docs/operator-guide/extensions/krakend.md
- docs/operator-guide/install-kuberocketci.md
- docs/operator-guide/upgrade/upgrade-krci-3.12.md
- docs/quick-start/platform-installation.md
- versioned_docs/version-3.10/operator-guide/upgrade/upgrade-krci-3.12.md
- versioned_docs/version-3.11/operator-guide/upgrade/upgrade-krci-3.12.md
- versioned_docs/version-3.12/operator-guide/extensions/krakend.md
- versioned_docs/version-3.12/operator-guide/install-kuberocketci.md
- versioned_docs/version-3.12/operator-guide/upgrade/upgrade-krci-3.12.md
- versioned_docs/version-3.12/quick-start/platform-installation.md
This change aligns documentation to the new 3.12.2 version.
npm ci && npm start && npm run spell-check
> docs: Update docs for 3-12-2 (#504)
